### ISSUE TITLE
MSAlertViewController checks on click MSAlertAction on isMemberOfClass

### ISSUE THREAD

**Issue by larryonoff** [szk-atmosphere/MSAlertController#11]
For the customization purposes my AlertAction class is inherited from MSAlertAction. Since there's isMemberOfClass check click handler doesn't work.

The same is with executePresentingAnimation for MSAlertController. 

Could you please change this checks from isMemberOfClass to isKindOfClass.

**Comment by szk-atmosphere** [comment]
I've finished changing  `isMemberOfClass ` to `isKindOfClass `.
Please update ver1.0.1 with `pod update`.

**Comment by larryonoff** [comment]
Thank you. It was really quick.
