### ISSUE TITLE
MSAlertAction enabled isn't handled properly 

### ISSUE THREAD

**Issue by larryonoff** [szk-atmosphere/MSAlertController#13]
Enabled property isn't applied If it is changed after controller is presented.

See example below. The example is taken from http://nshipster.com/uialertcontroller/.
```
alertController.addTextFieldWithConfigurationHandler { (textField) in
    textField.placeholder = "Login"

    NSNotificationCenter.defaultCenter().addObserverForName(UITextFieldTextDidChangeNotification, object: textField, queue: NSOperationQueue.mainQueue()) { (notification) in
        loginAction.enabled = textField.text != ""
    }
}
```

**Comment by marty-suzuki** [comment]
I've fixed this issue.
Please try ver1.0.2.

**Comment by larryonoff** [comment]
It works, but there are two bugs.
1. Keyboard is dismissed automatically when all characters are removed from the text field.
2. Keyboard is dismissed automatically when text field is empty and user enters the first symbol.
